[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.6.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[prune]
  go-tests = true
  unused-packages = true