[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "v1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "v1.3.1"

[[constraint]]
  name = "github.com/hashicorp/vault/api"
  version = "v0.8.3"

[[constraint]]
  name = "github.com/go-yaml/yaml"
