[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.1-coreos.6"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.6.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true