[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.6.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"

[[constraint]]
  name = "github.com/takama/daemon"
  version = "0.11.0"

[prune]
  go-tests = true
  unused-packages = true